import { describe, it, expect } from 'vitest';
import { generateAgentsMd, improveAgentsMd } from '../src/agents-md';
import type { StackInfo } from '../src/detect';
import { generateCLAUDEMd } from '../src/improve-claude-md';

const nodeStack: StackInfo = {
  language: 'node',
  packageManager: 'pnpm',
  commands: {
    build: 'pnpm build',
    test: 'pnpm test',
    lint: 'pnpm lint',
    typecheck: 'pnpm typecheck',
  },
  framework: 'Next.js',
};

const unknownStack: StackInfo = {
  language: 'unknown',
  packageManager: '',
  commands: {},
};

describe('generateAgentsMd', () => {
  it('generates fresh AGENTS.md with all expected sections', () => {
    const result = generateAgentsMd('my-project', nodeStack);

    expect(result).toContain('# my-project');
    expect(result).toContain('## Behavioral Boundaries');
    expect(result).toContain('### ALWAYS');
    expect(result).toContain('### ASK FIRST');
    expect(result).toContain('### NEVER');
    expect(result).toContain('## Architecture');
    expect(result).toContain('## Key Files');
    expect(result).toContain('## Development');
  });

  it('includes detected stack commands', () => {
    const result = generateAgentsMd('my-project', nodeStack);

    expect(result).toContain('pnpm build');
    expect(result).toContain('pnpm test');
    expect(result).toContain('pnpm lint');
    expect(result).toContain('pnpm typecheck');
  });

  it('points at docs/backlog/ for deferred work', () => {
    const result = generateAgentsMd('my-project', nodeStack);
    expect(result).toContain('docs/backlog/');
  });

  it('private setup note states init is non-destructive', () => {
    const result = generateAgentsMd('my-project', nodeStack, true);
    // The hedge Max had to hand-write is now folded into the tool.
    expect(result).toContain('After cloning, run');
    expect(result).toContain('only creates missing files');
    expect(result).toContain('--force');
    expect(result).toContain('untouched');
  });

  it('omits the private setup note under the shared profile', () => {
    const result = generateAgentsMd('my-project', nodeStack, false);
    expect(result).not.toContain('After cloning, run');
  });

  it('includes framework in header', () => {
    const result = generateAgentsMd('my-project', nodeStack);
    expect(result).toContain('Next.js');
  });

  it('does not reference CLAUDE.md as instructions source', () => {
    const result = generateAgentsMd('my-project', nodeStack);
    expect(result).not.toContain('See CLAUDE.md');
    expect(result).toMatch(/auto-generated by joycraft/i);
  });

  it('is shorter than CLAUDE.md for the same project', () => {
    const agentsMd = generateAgentsMd('my-project', nodeStack);
    const claudeMd = generateCLAUDEMd('my-project', nodeStack);
    expect(agentsMd.length).toBeLessThan(claudeMd.length);
  });

  it('handles unknown stack without errors', () => {
    const result = generateAgentsMd('my-project', unknownStack);
    expect(result).toContain('# my-project');
    expect(result).toContain('## Behavioral Boundaries');
  });
});

describe('improveAgentsMd', () => {
  it('adds missing sections to existing AGENTS.md', () => {
    const existing = '# My Project\n\nSome custom intro.\n';
    const result = improveAgentsMd(existing, nodeStack);

    expect(result).toContain('# My Project');
    expect(result).toContain('Some custom intro.');
    expect(result).toContain('## Behavioral Boundaries');
    expect(result).toContain('## Architecture');
    expect(result).toContain('## Key Files');
    expect(result).toContain('## Development');
  });

  it('preserves existing sections and does not duplicate', () => {
    const existing = '# My Project\n\n## Behavioral Boundaries\n\nMy custom boundaries.\n\n## Architecture\n\nMy architecture.\n';
    const result = improveAgentsMd(existing, nodeStack);

    expect(result).toContain('My custom boundaries.');
    expect(result).toContain('My architecture.');
    const boundaryMatches = result.match(/## Behavioral Boundaries/g);
    expect(boundaryMatches).toHaveLength(1);
    const archMatches = result.match(/## Architecture/g);
    expect(archMatches).toHaveLength(1);
    // Still adds missing sections
    expect(result).toContain('## Key Files');
    expect(result).toContain('## Development');
  });

  it('returns unchanged content when all sections exist', () => {
    const existing = [
      '# Project',
      '',
      '## Behavioral Boundaries',
      'rules here',
      '',
      '### External API Safety',
      '- safety rules here',
      '',
      '## Architecture',
      'arch here',
      '',
      '## Key Files',
      'files here',
      '',
      '## Development',
      'dev here',
      '',
    ].join('\n');

    const result = improveAgentsMd(existing, nodeStack);
    expect(result).toBe(existing);
  });
});

describe('product identity section in AGENTS.md', () => {
  const identity = {
    values: ['Ship small, dated changes'],
    glossary: { Harness: 'The set of always-injected instruction files' },
    taste: ['Prose over ceremony'],
  };

  it('appends one ## Product Identity section with all three subsections when content is supplied', () => {
    const base = generateAgentsMd('my-project', nodeStack);
    const result = improveAgentsMd(base, nodeStack, false, undefined, identity);

    const headers = result.match(/^## Product Identity\b/gm) ?? [];
    expect(headers.length).toBe(1);
    expect(result).toContain('### Values');
    expect(result).toContain('### Glossary');
    expect(result).toContain('### Taste');
    expect(result).toContain('Ship small, dated changes');
    expect(result).toContain('Harness');
    expect(result).toContain('Prose over ceremony');
  });

  it('stamps the section with a date and a review pointer', () => {
    const base = generateAgentsMd('my-project', nodeStack);
    const result = improveAgentsMd(base, nodeStack, false, undefined, identity);
    expect(result).toMatch(/_Added \d{4}-\d{2}-\d{2} — review at next optimize run_/);
  });

  it('emits only the subsections that have content', () => {
    const base = generateAgentsMd('my-project', nodeStack);
    const result = improveAgentsMd(base, nodeStack, false, undefined, {
      glossary: { Harness: 'always-injected instruction files' },
    });
    expect(result).toContain('## Product Identity');
    expect(result).toContain('### Glossary');
    expect(result).not.toContain('### Values');
    expect(result).not.toContain('### Taste');
  });

  it('does not append when a header already matches the product identity regex', () => {
    const base = generateAgentsMd('my-project', nodeStack) + '\n## Our Product Identity\n\nmine\n';
    const result = improveAgentsMd(base, nodeStack, false, undefined, identity);
    const headers = result.match(/^##.*Product Identity\b/gm) ?? [];
    expect(headers.length).toBe(1);
    expect(result).toContain('## Our Product Identity');
    expect(result).not.toContain('### Values');
  });

  it('emits nothing — no section, no TODO — when no identity content is supplied', () => {
    const base = generateAgentsMd('my-project', nodeStack);
    const result = improveAgentsMd(base, nodeStack);
    expect(result).not.toContain('Product Identity');
    expect(result).not.toMatch(/TODO.*[Ii]dentity/);
    expect(base).not.toContain('Product Identity');
  });

  it('treats empty strings and empty arrays as no content', () => {
    const base = generateAgentsMd('my-project', nodeStack);
    const result = improveAgentsMd(base, nodeStack, false, undefined, {
      values: ['', '  '],
      glossary: {},
      taste: [],
    });
    expect(result).not.toContain('Product Identity');
  });
});
