import { describe, it, expect } from 'vitest';
import { generateAgentsMd, improveAgentsMd } from '../src/agents-md';
import type { StackInfo } from '../src/detect';
import { generateCLAUDEMd } from '../src/improve-claude-md';

const nodeStack: StackInfo = {
  language: 'node',
  packageManager: 'pnpm',
  commands: {
    build: 'pnpm build',
    test: 'pnpm test',
    lint: 'pnpm lint',
    typecheck: 'pnpm typecheck',
  },
  framework: 'Next.js',
};

const unknownStack: StackInfo = {
  language: 'unknown',
  packageManager: '',
  commands: {},
};

describe('generateAgentsMd', () => {
  it('generates fresh AGENTS.md with all expected sections', () => {
    const result = generateAgentsMd('my-project', nodeStack);

    expect(result).toContain('# my-project');
    expect(result).toContain('## Behavioral Boundaries');
    expect(result).toContain('### ALWAYS');
    expect(result).toContain('### ASK FIRST');
    expect(result).toContain('### NEVER');
    expect(result).toContain('## Architecture');
    expect(result).toContain('## Key Files');
    expect(result).toContain('## Development');
  });

  it('includes detected stack commands', () => {
    const result = generateAgentsMd('my-project', nodeStack);

    expect(result).toContain('pnpm build');
    expect(result).toContain('pnpm test');
    expect(result).toContain('pnpm lint');
    expect(result).toContain('pnpm typecheck');
  });

  it('includes framework in header', () => {
    const result = generateAgentsMd('my-project', nodeStack);
    expect(result).toContain('Next.js');
  });

  it('references CLAUDE.md as source of truth', () => {
    const result = generateAgentsMd('my-project', nodeStack);
    expect(result).toContain('CLAUDE.md');
    expect(result).toMatch(/auto-generated by joycraft/i);
  });

  it('is shorter than CLAUDE.md for the same project', () => {
    const agentsMd = generateAgentsMd('my-project', nodeStack);
    const claudeMd = generateCLAUDEMd('my-project', nodeStack);
    expect(agentsMd.length).toBeLessThan(claudeMd.length);
  });

  it('handles unknown stack without errors', () => {
    const result = generateAgentsMd('my-project', unknownStack);
    expect(result).toContain('# my-project');
    expect(result).toContain('## Behavioral Boundaries');
  });
});

describe('improveAgentsMd', () => {
  it('adds missing sections to existing AGENTS.md', () => {
    const existing = '# My Project\n\nSome custom intro.\n';
    const result = improveAgentsMd(existing, nodeStack);

    expect(result).toContain('# My Project');
    expect(result).toContain('Some custom intro.');
    expect(result).toContain('## Behavioral Boundaries');
    expect(result).toContain('## Architecture');
    expect(result).toContain('## Key Files');
    expect(result).toContain('## Development');
  });

  it('preserves existing sections and does not duplicate', () => {
    const existing = '# My Project\n\n## Behavioral Boundaries\n\nMy custom boundaries.\n\n## Architecture\n\nMy architecture.\n';
    const result = improveAgentsMd(existing, nodeStack);

    expect(result).toContain('My custom boundaries.');
    expect(result).toContain('My architecture.');
    const boundaryMatches = result.match(/## Behavioral Boundaries/g);
    expect(boundaryMatches).toHaveLength(1);
    const archMatches = result.match(/## Architecture/g);
    expect(archMatches).toHaveLength(1);
    // Still adds missing sections
    expect(result).toContain('## Key Files');
    expect(result).toContain('## Development');
  });

  it('returns unchanged content when all sections exist', () => {
    const existing = [
      '# Project',
      '',
      '## Behavioral Boundaries',
      'rules here',
      '',
      '## Architecture',
      'arch here',
      '',
      '## Key Files',
      'files here',
      '',
      '## Development',
      'dev here',
      '',
    ].join('\n');

    const result = improveAgentsMd(existing, nodeStack);
    expect(result).toBe(existing);
  });
});
