import { describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  createReleasePreparationPlan,
  emitReleaseDescriptor,
  packReleaseArtifact,
  prepareReleaseBranch,
  prepareReleaseFiles,
  resolveReleaseVersion,
  hasUnpreparedProductChanges,
  resolveReleaseBaseline,
  resolveRetainedArtifact,
  createNpmProcessAdapter,
  syncReleasePullRequest,
  verifyReleaseCommit,
  isMergedReleasePreparationCommit,
} from '../scripts/release-preparation.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

function fixturePackage(version = '1.2.3'): string {
  const dir = mkdtempSync(join(tmpdir(), 'joycraft-release-'));
  const dist = join(dir, 'dist');
  mkdirSync(dist, { recursive: true });
  writeFileSync(join(dir, 'package.json'), JSON.stringify({
    name: 'release-fixture',
    version,
    files: ['dist'],
  }, null, 2) + '\n');
  writeFileSync(join(dist, 'joycraft-release.json'), JSON.stringify({
    schemaVersion: 1,
    releaseVersion: version,
    manifestSchemas: [1],
    autoSafeEligible: false,
  }, null, 2) + '\n');
  return dir;
}

describe('release preparation', () => {
  it('creates exactly one serialized PR plan for product changes', () => {
    const plan = createReleasePreparationPlan({
      changedFiles: ['src/upgrade.ts', 'tests/upgrade.test.ts'],
      releaseSha: 'abc123',
      version: '0.8.0',
    });

    expect(plan.shouldPrepare).toBe(true);
    expect(plan.releaseSha).toBe('abc123');
    expect(plan.pullRequest).toEqual(expect.objectContaining({
      base: 'main',
      head: plan.releaseBranch,
    }));
    expect(plan.pullRequest.body).toContain('Docs: none — release preparation metadata and descriptor are generated by the release workflow.');
    expect(plan.lockKey).toContain(plan.releaseBranch);
    expect(plan.actions).not.toContain('git push origin main');
    expect(plan.actions.filter((action: string) => action.includes('pull request'))).toHaveLength(1);
  });

  it('exposes the same release decision through the production CLI entry point', () => {
    const output = execFileSync(process.execPath, [
      join(ROOT, 'scripts/release-preparation.mjs'),
      'plan',
      '--release-sha',
      '0123456789012345678901234567890123456789',
      '--version',
      '0.8.0',
      '--file',
      'src/cli.ts',
    ], { encoding: 'utf8' });
    expect(JSON.parse(output)).toEqual(expect.objectContaining({ shouldPrepare: true, releaseSha: '0123456789012345678901234567890123456789' }));
  });

  it('does not plan a release for docs-only changes', () => {
    const plan = createReleasePreparationPlan({
      changedFiles: ['docs/guides/upgrading.md', 'README.md', 'CHANGELOG.md'],
      releaseSha: 'docs123',
      version: '0.8.0',
    });

    expect(plan.shouldPrepare).toBe(false);
    expect(plan.pullRequest).toBeUndefined();
  });

  it('does not treat harness docs, tests, or release plumbing as package changes', () => {
    const plan = createReleasePreparationPlan({
      changedFiles: ['AGENTS.md', 'CLAUDE.md', 'tests/release-preparation.test.ts', 'scripts/release-preparation.mjs', '.github/workflows/publish.yml'],
      releaseSha: 'metadata123',
      version: '0.8.0',
    });

    expect(plan.shouldPrepare).toBe(false);
  });

  it('does not prepare a second release for a verified merged preparation PR', () => {
    const plan = createReleasePreparationPlan({
      changedFiles: ['package.json', 'src/joycraft-release.json'],
      releaseSha: 'merged-release-sha',
      version: '0.8.0',
      releasePreparationMerge: true,
    });

    expect(plan).toEqual(expect.objectContaining({ shouldPrepare: false, reason: 'release-preparation-merge' }));
    expect(createReleasePreparationPlan({
      changedFiles: ['package.json'],
      releaseSha: 'dependency-change-sha',
      version: '0.8.0',
    }).shouldPrepare).toBe(true);
  });

  it('uses the commit-to-PR association instead of guessing from a commit message', async () => {
    await expect(isMergedReleasePreparationCommit({
      repository: 'maksutovic/joycraft',
      releaseSha: 'merged-sha',
      run: async () => ({
        stdout: JSON.stringify([{ base: { ref: 'main' }, head: { ref: 'release/joycraft' }, merged_at: '2026-09-06T00:00:00Z' }]),
        stderr: '',
      }),
    })).resolves.toBe(true);
    await expect(isMergedReleasePreparationCommit({
      repository: 'maksutovic/joycraft',
      releaseSha: 'unmerged-sha',
      run: async () => ({
        stdout: JSON.stringify([{ base: { ref: 'main' }, head: { ref: 'feature/other' }, merged_at: null }]),
        stderr: '',
      }),
    })).resolves.toBe(false);
  });

  it('coalesces docs pushes after a prepared baseline while retaining later product changes', async () => {
    const root = mkdtempSync(join(tmpdir(), 'joycraft-baseline-'));
    mkdirSync(join(root, 'src'), { recursive: true });
    const git = (...args: string[]) => execFileSync('git', args, { cwd: root, encoding: 'utf8' });
    git('init', '-b', 'main');
    git('config', 'user.name', 'fixture');
    git('config', 'user.email', 'fixture@example.invalid');
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'release-fixture', version: '1.2.3' }, null, 2) + '\n');
    writeFileSync(join(root, 'src/joycraft-release.json'), JSON.stringify({ schemaVersion: 1, releaseVersion: '1.2.3', manifestSchemas: [1], autoSafeEligible: false }, null, 2) + '\n');
    writeFileSync(join(root, 'src/old.ts'), 'export const old = true;\n');
    writeFileSync(join(root, 'README.md'), 'base\n');
    git('add', '.');
    git('commit', '-m', 'base');
    const baselineSha = git('rev-parse', 'HEAD').trim();
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'release-fixture', version: '1.2.4' }, null, 2) + '\n');
    writeFileSync(join(root, 'src/joycraft-release.json'), JSON.stringify({ schemaVersion: 1, releaseVersion: '1.2.4', manifestSchemas: [1], autoSafeEligible: false }, null, 2) + '\n');
    writeFileSync(join(root, 'README.md'), 'docs changed\n');
    git('add', '.');
    git('commit', '-m', 'prepared metadata and docs');
    const docsSha = git('rev-parse', 'HEAD').trim();
    await expect(hasUnpreparedProductChanges({ cwd: root, baselineSha, currentSha: docsSha })).resolves.toEqual({
      hasUnpreparedProductChanges: false,
      files: ['README.md'],
    });
    writeFileSync(join(root, 'src/runtime.ts'), 'export const changed = true;\n');
    git('add', 'src/runtime.ts');
    git('commit', '-m', 'product change');
    const productSha = git('rev-parse', 'HEAD').trim();
    await expect(hasUnpreparedProductChanges({ cwd: root, baselineSha, currentSha: productSha })).resolves.toEqual(expect.objectContaining({
      hasUnpreparedProductChanges: true,
    }));
    rmSync(join(root, 'src/old.ts'));
    git('add', '-u', 'src/old.ts');
    git('commit', '-m', 'remove product file');
    const deletionSha = git('rev-parse', 'HEAD').trim();
    await expect(hasUnpreparedProductChanges({ cwd: root, baselineSha, currentSha: deletionSha })).resolves.toEqual(expect.objectContaining({
      hasUnpreparedProductChanges: true,
      files: expect.arrayContaining(['src/old.ts']),
    }));
  });

  it('uses durable open and merged baselines and reserves the merged version', async () => {
    const calls: string[][] = [];
    const run = async (_command: string, args: string[]) => {
      calls.push(args);
      if (args[0] === 'api') return { stdout: JSON.stringify([{ base: { ref: 'main' }, head: { ref: 'release/joycraft', sha: 'a'.repeat(40) }, merge_commit_sha: 'b'.repeat(40), merged_at: '2026-09-06T00:00:00Z' }]), stderr: '' };
      if (args[0] === 'show') return { stdout: JSON.stringify({ version: '0.7.14' }), stderr: '' };
      return { stdout: '', stderr: '' };
    };
    await expect(resolveReleaseBaseline({ repository: 'owner/repo', currentSha: 'b'.repeat(40), run })).resolves.toEqual({
      baselineSha: 'b'.repeat(40), source: 'merged-release-pr', reservedVersion: '0.7.14',
    });
    expect(calls.some(args => args[0] === 'api')).toBe(true);

    const mergedCalls: string[][] = [];
    const mergedRun = async (_command: string, args: string[]) => {
      mergedCalls.push(args);
      if (args[0] === 'api') return { stdout: '[]', stderr: '' };
      if (args[0] === 'pr' && args.includes('--state') && args.includes('merged')) return { stdout: `${'c'.repeat(40)}\n`, stderr: '' };
      if (args[0] === 'show') return { stdout: JSON.stringify({ version: '0.7.14' }), stderr: '' };
      if (args[0] === 'ls-remote') return { stdout: `${'d'.repeat(40)}\trefs/heads/release/joycraft\n`, stderr: '' };
      return { stdout: '', stderr: '' };
    };
    await expect(resolveReleaseBaseline({ repository: 'owner/repo', currentSha: 'e'.repeat(40), run: mergedRun })).resolves.toEqual({
      baselineSha: 'c'.repeat(40), source: 'latest-merged-release-pr', reservedVersion: '0.7.14',
    });
    expect(mergedCalls.findIndex(args => args[0] === 'pr' && args.includes('merged'))).toBeGreaterThanOrEqual(0);
    expect(mergedCalls.findIndex(args => args[0] === 'ls-remote')).toBe(-1);
  });

  it('resolves a release version and fails closed on registry errors', async () => {
    await expect(resolveReleaseVersion({
      packageName: 'joycraft',
      localVersion: '0.7.13',
      registryLookup: async () => ({ version: '0.7.12' }),
    })).resolves.toEqual(expect.objectContaining({ version: '0.7.13' }));

    await expect(resolveReleaseVersion({
      packageName: 'joycraft',
      localVersion: '0.7.13',
      registryLookup: async () => { throw new Error('registry unavailable'); },
    })).resolves.toEqual(expect.objectContaining({
      ok: false,
      error: expect.stringContaining('registry unavailable'),
    }));

    await expect(resolveReleaseVersion({
      packageName: 'joycraft',
      localVersion: '0.7.14',
      registryLookup: async () => ({ version: '0.7.13', versions: ['0.7.13', '0.7.14'], distTags: { latest: '0.7.13', candidate: '0.7.14' } }),
    })).resolves.toEqual(expect.objectContaining({ ok: true, version: '0.7.15' }));
    await expect(resolveReleaseVersion({
      packageName: 'joycraft',
      localVersion: '0.8.0',
      registryLookup: async () => ({ version: '0.7.13', versions: ['0.7.13'], distTags: {} }),
      reservedVersions: ['0.8.0'],
    })).resolves.toEqual(expect.objectContaining({ ok: true, version: '0.8.1' }));
    await expect(resolveReleaseVersion({
      packageName: 'joycraft',
      localVersion: '0.7.13',
      preparedVersion: '0.7.14',
      registryLookup: async () => ({ version: '0.7.13', versions: ['0.7.13'], distTags: {} }),
    })).resolves.toEqual(expect.objectContaining({ ok: true, version: '0.7.14' }));
  });

  it('updates package and tracked descriptor together, then emits the exact dist descriptor', () => {
    const cwd = mkdtempSync(join(tmpdir(), 'joycraft-descriptor-'));
    mkdirSync(join(cwd, 'src'), { recursive: true });
    writeFileSync(join(cwd, 'package.json'), JSON.stringify({ name: 'release-fixture', version: '1.2.3' }, null, 2) + '\n');
    writeFileSync(join(cwd, 'src/joycraft-release.json'), JSON.stringify({
      schemaVersion: 1, releaseVersion: '1.2.3', manifestSchemas: [1], autoSafeEligible: false,
    }, null, 2) + '\n');

    prepareReleaseFiles({ cwd, version: '1.2.4' });
    const emitted = emitReleaseDescriptor({ cwd });
    expect(JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8')).version).toBe('1.2.4');
    expect(JSON.parse(readFileSync(join(cwd, 'src/joycraft-release.json'), 'utf8'))).toEqual(emitted.descriptor);
    expect(JSON.parse(readFileSync(join(cwd, 'dist/joycraft-release.json'), 'utf8'))).toEqual({
      schemaVersion: 1, releaseVersion: '1.2.4', manifestSchemas: [1], autoSafeEligible: false,
    });
  });

  it('rejects a checked-out commit that does not match the immutable release SHA', async () => {
    const expected = '0123456789012345678901234567890123456789';
    await expect(verifyReleaseCommit({
      releaseSha: expected,
      run: async (_command: string, args: string[]) => {
        if (args[0] === 'rev-parse') return { stdout: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n', stderr: '' };
        return { stdout: '', stderr: '' };
      },
    })).rejects.toThrow(/does not match/);
  });

  it('rejects an immutable SHA that is not merged into main', async () => {
    const expected = '0123456789012345678901234567890123456789';
    await expect(verifyReleaseCommit({
      releaseSha: expected,
      run: async (_command: string, args: string[]) => {
        if (args[0] === 'rev-parse') return { stdout: `${expected}\n`, stderr: '' };
        if (args[0] === 'merge-base') throw new Error('not an ancestor');
        return { stdout: '', stderr: '' };
      },
    })).rejects.toThrow(/not merged/);
  });

  it('packs once, retains a sha512 digest, and binds the descriptor to the version', async () => {
    const cwd = fixturePackage('1.2.3');
    const artifactDir = join(cwd, 'retained');
    let packCalls = 0;
    const result = await packReleaseArtifact({
      cwd,
      artifactDir,
      releaseSha: 'reviewed-sha',
      run: async (file: string, args: string[]) => {
        packCalls += 1;
        return new Promise<{ stdout: string; stderr: string }>((resolve, reject) => {
          execFileSync(file, args, { cwd, stdio: 'pipe' });
          resolve({ stdout: JSON.stringify([{ filename: join(artifactDir, 'release-fixture-1.2.3.tgz'),
            package: { name: 'release-fixture', version: '1.2.3' } }]), stderr: '' });
        });
      },
    });

    expect(packCalls).toBe(1);
    expect(result.tarball).toMatch(/release-fixture-1\.2\.3\.tgz$/);
    expect(result.integrity).toMatch(/^sha512-[A-Za-z0-9+/]+=*$/);
    expect(result.descriptor).toEqual(expect.objectContaining({ releaseVersion: '1.2.3' }));
    expect(readFileSync(result.manifestPath, 'utf8')).toContain('reviewed-sha');
  });

  it('accepts a matching retained artifact and rejects altered integrity or provenance', async () => {
    const cwd = fixturePackage('1.2.3');
    const artifactDir = join(cwd, 'retained');
    const packed = await packReleaseArtifact({ cwd, artifactDir, releaseSha: 'reviewed-sha' });

    await expect(resolveRetainedArtifact({
      manifestPath: packed.manifestPath,
      expected: { releaseSha: 'reviewed-sha', version: '1.2.3', packageName: 'release-fixture' },
    })).resolves.toEqual(expect.objectContaining({ tarball: packed.tarball, integrity: packed.integrity }));

    const manifest = JSON.parse(readFileSync(packed.manifestPath, 'utf8'));
    manifest.releaseSha = 'different-sha';
    writeFileSync(packed.manifestPath, JSON.stringify(manifest));
    await expect(resolveRetainedArtifact({
      manifestPath: packed.manifestPath,
      expected: { releaseSha: 'reviewed-sha', version: '1.2.3', packageName: 'release-fixture' },
    })).rejects.toThrow(/provenance|release SHA/i);
  });

  it('rejects a package whose descriptor is outside the approved dist path', async () => {
    const cwd = fixturePackage('1.2.3');
    const distDescriptor = join(cwd, 'dist/joycraft-release.json');
    const rootDescriptor = join(cwd, 'joycraft-release.json');
    writeFileSync(rootDescriptor, readFileSync(distDescriptor));
    rmSync(distDescriptor);
    await expect(packReleaseArtifact({ cwd, artifactDir: join(cwd, 'retained'), releaseSha: 'reviewed-sha' })).rejects.toThrow(/missing dist/i);
  });

  it('retains a reviewed automation declaration but does not carry it into the next release', async () => {
    const cwd = fixturePackage('1.2.3');
    try {
      const descriptorPath = join(cwd, 'src/joycraft-release.json');
      mkdirSync(join(cwd, 'src'), { recursive: true });
      const descriptor = JSON.parse(readFileSync(join(cwd, 'dist/joycraft-release.json'), 'utf8'));
      descriptor.autoSafeEligible = true;
      writeFileSync(descriptorPath, JSON.stringify(descriptor));
      expect(emitReleaseDescriptor({ cwd }).descriptor.autoSafeEligible).toBe(true);
      const packed = await packReleaseArtifact({ cwd, artifactDir: join(cwd, 'retained'), releaseSha: 'reviewed-sha' });
      const retained = await resolveRetainedArtifact({ manifestPath: packed.manifestPath, expected: { releaseSha: 'reviewed-sha', version: '1.2.3', packageName: 'release-fixture' } });
      expect(retained.descriptor.autoSafeEligible).toBe(true);
      prepareReleaseFiles({ cwd, version: '1.2.4' });
      expect(JSON.parse(readFileSync(descriptorPath, 'utf8')).autoSafeEligible).toBe(false);
    } finally { rmSync(cwd, { recursive: true, force: true }); }
  });

  it('publishes the retained tarball with argument-array candidate semantics', async () => {
    const calls: Array<{ command: string; args: string[] }> = [];
    const npm = createNpmProcessAdapter({
      run: async (command: string, args: string[]) => {
        calls.push({ command, args });
        return { stdout: '', stderr: '' };
      },
    });

    await npm.publishCandidate('/tmp/release-fixture.tgz');
    expect(calls).toHaveLength(1);
    expect(calls[0].args).toEqual(['publish', '/tmp/release-fixture.tgz', '--access', 'public', '--tag', 'candidate']);
    expect(calls[0].args).not.toContain('latest');
  });

  it('refreshes an existing release branch with ordinary Git operations and edits one PR', async () => {
    const root = mkdtempSync(join(tmpdir(), 'joycraft-git-release-'));
    const remote = join(root, 'remote.git');
    const seed = join(root, 'seed');
    const work = join(root, 'work');
    execFileSync('git', ['init', '--bare', remote]);
    execFileSync('git', ['init', '-b', 'main', seed]);
    const git = (cwd: string, ...args: string[]) => execFileSync('git', args, { cwd, encoding: 'utf8' });
    git(seed, 'config', 'user.name', 'fixture');
    git(seed, 'config', 'user.email', 'fixture@example.invalid');
    mkdirSync(join(seed, 'src'), { recursive: true });
    writeFileSync(join(seed, 'package.json'), JSON.stringify({ name: 'release-fixture', version: '1.2.3' }, null, 2) + '\n');
    writeFileSync(join(seed, 'src/joycraft-release.json'), JSON.stringify({ schemaVersion: 1, releaseVersion: '1.2.3', manifestSchemas: [1], autoSafeEligible: false }, null, 2) + '\n');
    writeFileSync(join(seed, 'src/runtime.js'), 'export const release = true;\n');
    git(seed, 'add', '.');
    git(seed, 'commit', '-m', 'initial');
    git(seed, 'remote', 'add', 'origin', remote);
    git(seed, 'push', 'origin', 'main');
    execFileSync('git', ['clone', '-b', 'main', remote, work]);
    git(work, 'config', 'user.name', 'fixture');
    git(work, 'config', 'user.email', 'fixture@example.invalid');
    git(work, 'switch', '-c', 'release/joycraft');
    prepareReleaseFiles({ cwd: work, version: '1.2.4' });
    writeFileSync(join(work, 'RELEASE-NOTE'), 'previous candidate\n');
    git(work, 'add', '.');
    git(work, 'commit', '-m', 'previous release preparation');
    git(work, 'push', 'origin', 'release/joycraft');
    git(work, 'switch', 'main');
    writeFileSync(join(work, 'src/runtime.js'), 'export const release = false;\n');
    writeFileSync(join(work, 'package.json'), JSON.stringify({ name: 'release-fixture', version: '1.2.5' }, null, 2) + '\n');
    writeFileSync(join(work, 'src/joycraft-release.json'), JSON.stringify({ schemaVersion: 1, releaseVersion: '1.2.5', manifestSchemas: [1], autoSafeEligible: false }, null, 2) + '\n');
    git(work, 'add', 'src/runtime.js', 'package.json', 'src/joycraft-release.json');
    git(work, 'commit', '-m', 'product change with explicit version');
    git(work, 'push', 'origin', 'main');
    const mainSha = git(work, 'rev-parse', 'HEAD').trim();

    await prepareReleaseBranch({ cwd: work, mainSha, version: '1.2.6' });
    const remoteVersion = git(work, 'show', 'HEAD:package.json');
    const remoteDescriptor = git(work, 'show', 'HEAD:src/joycraft-release.json');
    expect(JSON.parse(remoteVersion).version).toBe('1.2.6');
    expect(JSON.parse(remoteDescriptor).releaseVersion).toBe('1.2.6');
    expect(readFileSync(join(work, 'src/runtime.js'), 'utf8')).toBe('export const release = false;\n');
    expect(git(work, 'log', '--merges', '--format=%P').trim().split(' ')).toHaveLength(2);
    expect(git(work, 'log', '-1', '--format=%s')).toBe('release: prepare v1.2.6\n');

    const ghCalls: string[][] = [];
    await syncReleasePullRequest({
      version: '1.2.6',
      run: async (command: string, args: string[]) => {
        ghCalls.push([command, ...args]);
        return { stdout: args[1] === 'list' ? '42\n' : '', stderr: '' };
      },
    });
    expect(ghCalls).toHaveLength(2);
    expect(ghCalls[1]).toContain('edit');
    expect(ghCalls[1].join(' ')).toContain('Docs: none');
    expect(ghCalls.some(call => call.includes('create'))).toBe(false);
  });
});

describe('production workflow contracts', () => {
  const publish = readFileSync(join(ROOT, '.github/workflows/publish.yml'), 'utf8');

  it('releases main pushes automatically without a release PR', () => {
    expect(publish).toMatch(/on:\s*\n\s+push:\s*\n\s+branches: \[main\]/);
    expect(publish).not.toContain('pull_request');
    expect(publish).not.toContain('release/joycraft');
    expect(publish).toContain('node scripts/automatic-release.mjs');
    expect(publish).toContain("github.event_name == 'push'");
    expect(existsSync(join(ROOT, '.github/workflows/release-prepare.yml'))).toBe(false);
  });

  it('retains immutable source, OIDC, serialized publication, and packaged verification', () => {
    expect(publish).toContain('ref: ${{ inputs.release_sha || github.sha }}');
    expect(publish).toContain('id-token: write');
    expect(publish).toContain('verify-commit');
    expect(publish).toMatch(/concurrency:[\s\S]*cancel-in-progress:\s*false/);
    expect(publish).toContain('node-version: 24.20.0');
    expect(publish).toContain('npm@11.19.0');
    expect(publish).toContain('version: 10.19.0');
    expect(publish).toContain('steps.artifact.outputs.tarball');
    expect(publish).toContain('uses: ./.github/workflows/test.yml');
    expect(publish).toContain('--tag latest');
    expect(publish).toContain('needs: [pack, compatibility]');
    expect(publish).not.toContain('JOYCRAFT_NPM_PROMOTION_TOKEN');
    expect(publish).not.toContain('git push origin main');
  });
});
