import type { StackInfo } from './detect.js';

interface Section {
  header: string;
  content: string;
}

function parseSections(markdown: string): Section[] {
  const lines = markdown.split('\n');
  const sections: Section[] = [];
  let currentHeader = '';
  let currentLines: string[] = [];

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (currentHeader || currentLines.length > 0) {
        sections.push({ header: currentHeader, content: currentLines.join('\n') });
      }
      currentHeader = line;
      currentLines = [];
    } else {
      currentLines.push(line);
    }
  }

  if (currentHeader || currentLines.length > 0) {
    sections.push({ header: currentHeader, content: currentLines.join('\n') });
  }

  return sections;
}

function hasSection(sections: Section[], pattern: RegExp): boolean {
  return sections.some(s => pattern.test(s.header));
}

function generateCommandsBlock(stack: StackInfo): string {
  const lines: string[] = ['```bash'];
  if (stack.commands.build) lines.push(stack.commands.build);
  if (stack.commands.test) lines.push(stack.commands.test);
  if (stack.commands.lint) lines.push(stack.commands.lint);
  if (stack.commands.typecheck) lines.push(stack.commands.typecheck);
  if (stack.commands.deploy) lines.push(stack.commands.deploy);
  lines.push('```');
  return lines.join('\n');
}

function generateBoundariesSection(): string {
  return `## Behavioral Boundaries

### ALWAYS
- Run tests and type-check before committing
- Follow existing code patterns and style

### ASK FIRST
- Adding new dependencies
- Changing auth or data models
- Any destructive operation

### NEVER
- Push to main without approval
- Skip tests or type-checking
- Hardcode secrets or credentials`;
}

function generateDevelopmentSection(stack: StackInfo): string {
  return `## Development

${generateCommandsBlock(stack)}`;
}

function generateArchitectureSection(): string {
  return `## Architecture

_TODO: Add a compact directory tree and one-paragraph summary._`;
}

function generateKeyFilesSection(): string {
  return `## Key Files

| File | Purpose |
|------|---------|
| _TODO_ | _Add key files_ |`;
}

export function generateAgentsMd(projectName: string, stack: StackInfo): string {
  const frameworkNote = stack.framework ? ` (${stack.framework})` : '';
  const langLabel = stack.language === 'unknown' ? '' : ` | **Stack:** ${stack.language}${frameworkNote}`;

  const lines: string[] = [
    `# ${projectName}`,
    '',
    `**Component:** _TODO: describe what this project is_${langLabel}`,
    '',
    '> Auto-generated by Joycraft. See CLAUDE.md for detailed instructions.',
    '',
    '---',
    '',
    generateBoundariesSection(),
    '',
    generateArchitectureSection(),
    '',
    generateKeyFilesSection(),
    '',
    generateDevelopmentSection(stack),
    '',
  ];

  return lines.join('\n');
}

export function improveAgentsMd(existing: string, stack: StackInfo): string {
  const sections = parseSections(existing);
  const additions: string[] = [];

  if (!hasSection(sections, /behavioral\s*boundar/i)) {
    additions.push(generateBoundariesSection());
  }

  if (!hasSection(sections, /architecture/i)) {
    additions.push(generateArchitectureSection());
  }

  if (!hasSection(sections, /key\s*files/i)) {
    additions.push(generateKeyFilesSection());
  }

  if (!hasSection(sections, /development/i)) {
    additions.push(generateDevelopmentSection(stack));
  }

  if (additions.length === 0) {
    return existing;
  }

  const trimmed = existing.trimEnd();
  return trimmed + '\n\n' + additions.join('\n\n') + '\n';
}
