import type { StackInfo } from './detect.js';
import {
  ensureExecutionProfileSection,
  renderExecutionProfileSection,
  type ExecutionProfile,
} from './execution-profile.js';
import {
  generateBoundariesSection,
  generateExternalApiSafetySection,
  generatePrivateSetupNote,
  PRIVATE_SETUP_NOTE_MARKER,
} from './improve-claude-md.js';

interface Section {
  header: string;
  content: string;
}

function parseSections(markdown: string): Section[] {
  const lines = markdown.split('\n');
  const sections: Section[] = [];
  let currentHeader = '';
  let currentLines: string[] = [];

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (currentHeader || currentLines.length > 0) {
        sections.push({ header: currentHeader, content: currentLines.join('\n') });
      }
      currentHeader = line;
      currentLines = [];
    } else {
      currentLines.push(line);
    }
  }

  if (currentHeader || currentLines.length > 0) {
    sections.push({ header: currentHeader, content: currentLines.join('\n') });
  }

  return sections;
}

function hasSection(sections: Section[], pattern: RegExp): boolean {
  return sections.some(s => pattern.test(s.header));
}

function generateCommandsBlock(stack: StackInfo): string {
  const lines: string[] = ['```bash'];
  if (stack.commands.build) lines.push(stack.commands.build);
  if (stack.commands.test) lines.push(stack.commands.test);
  if (stack.commands.lint) lines.push(stack.commands.lint);
  if (stack.commands.typecheck) lines.push(stack.commands.typecheck);
  if (stack.commands.deploy) lines.push(stack.commands.deploy);
  lines.push('```');
  return lines.join('\n');
}

function generateDevelopmentSection(stack: StackInfo): string {
  return `## Development\n\n${generateCommandsBlock(stack)}\n\n**Deferred work → \`docs/backlog/\`.** Ideas and follow-ups surfaced mid-sprint that can't be taken on now go to \`docs/backlog/\` (one file per item) so the current spec stays focused. Promote an entry to a Feature Brief under \`docs/features/<slug>/\` when ready to build it.`;
}

function generateArchitectureSection(): string {
  return `## Architecture\n\n_TODO: Add a compact directory tree and one-paragraph summary._`;
}

function generateKeyFilesSection(): string {
  return `## Key Files\n\n| File | Purpose |\n|------|---------|\n| _TODO_ | _Add key files_ |`;
}

export function generateAgentsMd(
  projectName: string,
  stack: StackInfo,
  privateProfile = false,
  executionProfile?: ExecutionProfile,
): string {
  const frameworkNote = stack.framework ? ` (${stack.framework})` : '';
  const langLabel = stack.language === 'unknown' ? '' : ` | **Stack:** ${stack.language}${frameworkNote}`;

  const lines: string[] = [
    `# ${projectName}`,
    '',
    `**Component:** _TODO: describe what this project is_${langLabel}`,
    '',
    '> Auto-generated by Joycraft.',
    '',
    '---',
    '',
    generateBoundariesSection(),
    generateExternalApiSafetySection(),
    '',
    generateArchitectureSection(),
    '',
    generateKeyFilesSection(),
    '',
    generateDevelopmentSection(stack),
    '',
  ];

  if (executionProfile) {
    lines.push(renderExecutionProfileSection(executionProfile), '');
  }

  if (privateProfile) {
    lines.push(generatePrivateSetupNote(), '');
  }

  return lines.join('\n');
}

export function improveAgentsMd(
  existing: string,
  stack: StackInfo,
  privateProfile = false,
  executionProfile?: ExecutionProfile,
): string {
  const sections = parseSections(existing);
  const additions: string[] = [];

  if (!hasSection(sections, /behavioral\s*boundar/i)) {
    additions.push(generateBoundariesSection());
  }

  if (!/external\s*api\s*safety/i.test(existing)) {
    additions.push(generateExternalApiSafetySection());
  }

  if (!hasSection(sections, /architecture/i)) {
    additions.push(generateArchitectureSection());
  }

  if (!hasSection(sections, /key\s*files/i)) {
    additions.push(generateKeyFilesSection());
  }

  if (!hasSection(sections, /development/i)) {
    additions.push(generateDevelopmentSection(stack));
  }

  if (privateProfile && !existing.includes(PRIVATE_SETUP_NOTE_MARKER)) {
    additions.push(generatePrivateSetupNote());
  }

  if (additions.length === 0) {
    // Sentinel-based, not heading-based: an existing profile region is opaque
    // user data and must come back byte-identical.
    return ensureExecutionProfileSection(existing, executionProfile);
  }

  const trimmed = existing.trimEnd();
  const merged = trimmed + '\n\n' + additions.join('\n\n') + '\n';
  return ensureExecutionProfileSection(merged, executionProfile);
}
